### ISSUE TITLE
Google maps api key for ios

### ISSUE THREAD

**Issue by nelsoncampoos** [lucasmontano/openweathermap-flutter#7]
I was configuring the ios project to use the google maps API, but I copied the api key from the native android project and I think the api key is disabled for use on ios, beacuse i tested in iphone and android emulator and the android emulator the google maps open, and iphone emulator dont funtion the maps view, if someone has the google maps api key for ios i would be grateful.

**Comment by jacobaraujo7** [comment]
@lucasmontano
